<?php

/**
 * @file
 * Main module file.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Form\FormState;
use Drupal\Core\Url;
use Drupal\media_directories_ui\Form\FileUploadForm;
use Drupal\media_directories_ui\Form\OEmbedForm;

/**
 * Implements hook_theme().
 */
function media_directories_ui_theme($existing, $type, $theme, $path) {
  return [
    'media_directories_browser' => [
      'render element' => 'browser',
    ],
    'dropzonejs__media_upload' => [
      'base hook' => 'dropzonejs',
      'template' => 'dropzonejs--media-upload',
    ],
    'media_directories_add' => [
      'variables' => [
        'selected_type' => NULL,
        'active_directory' => NULL,
        'target_bundles' => NULL,
      ],
    ],
    'views_view_unformatted__media_directory_browser' => [
      'base hook' => 'views_view_unformatted',
      'template' => 'views-view-unformatted--media-directory-browser',
    ],
  ];
}

/**
 * Implements hook_css_alter().
 */
function media_directories_ui_css_alter(&$css, AttachedAssetsInterface $assets) {
  $route = 'entity_browser.directory_browser';

  if (Drupal::routeMatch()->getRouteName() === $route) {
    unset($css[drupal_get_path('module', 'entity_browser') . '/css/entity_browser.entity_browser.css']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function media_directories_ui_preprocess_views_view_unformatted__media_directory_browser(&$variables) {
  foreach ($variables['rows'] as &$row) {
    /** @var \Drupal\media\Entity\Media $entity */
    $entity = $row['content']['#row']->_entity;
    $entity_id = $entity->id();
    $row['attributes']->setAttribute('data-mid', $entity_id);
    $row['attributes']->addClass('media-item');
    $row['attributes']->addClass('media-type--' . $entity->bundle());
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function media_directories_ui_preprocess_views_view_fields__media_directory_browser(&$variables) {
  foreach ($variables['fields'] as $name => &$field) {
    /** @var \Drupal\media\Entity\Media $entity */
    $entity = $variables['row']->_entity;

    if ($name === 'thumbnail__target_id') {
      $field->wrapper_attributes->addClass('media-thumbnail');
      $field->wrapper_attributes->addClass('media-thumbnail--' . $entity->bundle());
    }
    elseif ($name === 'name') {
      $field->wrapper_attributes->addClass('media-name');
      $field->wrapper_attributes->addClass('media-name--' . $entity->bundle());
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function media_directories_ui_preprocess_media_directories_add(&$variables) {
  /** @var \Drupal\media\Entity\MediaType[] $types */
  $types = \Drupal::entityTypeManager()->getStorage('media_type')->loadMultiple();

  $variables['links'] = [
    '#theme' => 'links',
    '#links' => [],
    '#attributes' => [
      'class' => ['media-library-menu', 'js-media-library-menu'],
    ],
  ];

  foreach ($types as $type) {
    $variables['links']['#links'][$type->id()] = [
      'title' => $type->label(),
      'url' => Url::fromRoute('media_directories_ui.media.add', [], [
        'query' => [
          'media_type' => $type->id(),
          'active_directory' => $variables['active_directory'],
          'target_bundles' => $variables['target_bundles'],
        ],
        ]),
      'attributes' => ['class' => ['use-ajax', 'media-library-menu__link']],
    ];

    if ($variables['selected_type'] === $type->id()) {
      $variables['links']['#links'][$type->id()]['attributes']['class'][] = 'active';
    }
  }

  $type = $types[$variables['selected_type']];

  $form_state = new FormState();
  $form_state->setValue('media_type', $type);

  $source_field = $type->getSource()->getConfiguration()['source_field'];
  $field_config = \Drupal::entityTypeManager()->getStorage('field_config')->load('media.' . $type->id() .'.' . $source_field);

  $form_state = new FormState();
  $form_state->set('media_type', $type);
  $form_state->set('active_directory', $variables['active_directory']);
  $form_state->set('target_bundles', $variables['target_bundles']);

  if (in_array($field_config->getType(), ['file', 'image'])) {
    $variables['media_form'] = \Drupal::formBuilder()->buildForm(FileUploadForm::class, $form_state);
  }
  else {
    $variables['media_form'] = \Drupal::formBuilder()->buildForm(OEmbedForm::class, $form_state);
  }

}
